### ISSUE TITLE
Increase group summary length to > 50 chars

### ISSUE THREAD

**Issue by stefanbc** [radiushq/feature-requests#5]
Recommend to increase the summary for a group to at least 150 chars since 50 chars is just to small of a summary.

**Comment by smuui** [comment]
Hey @stefanbc 👋 - thanks for this request! So, the reason the limit is set to 50 is due to the design of the upcoming group listings (see below):-

![Screenshot 2024-01-14 at 16 19 02](https://github.com/radiushq/feature-requests/assets/156589576/dcc44a21-21e2-4fc0-b622-253ab2cbf5bc)

It's just a short summary/tagline to explain what the group is about, just in case the group name isn't descriptive enough.  I agree that 50 may be a little on the low side though, so I'll increase this to 70 for now, and also include some explanatory text below the form field with an example, so people know this isn't supposed to be a full summary.

Thanks again for the feedback!
